### ISSUE TITLE
atom index notation

### ISSUE THREAD

**Issue by bdolsen** [tzyyshyanglin/BigSMILES#2]
The atom index notation is really complicated.  It leads to long, unwieldy lists.  I have two suggestions to simplify.  First, allow the use of range notation to eliminate lists that go 1, 2, 3, 4, 5, ...
Second, maybe you could allow entire stochastic objects to be mapped at once.  However, this does effectively deal with a large fraction of the situations where characterization is performed on a precursor molecule.

**Comment by tzyyshyanglin** [comment]
this should be resolved by the interface
